### ISSUE TITLE
map is black when shown in rviz

### ISSUE THREAD

**Issue by ianloefgren** [COHRINT/gazebo_world_builder#2]
changing free and occupied thresholds to normal values did not fix issue

**Comment by mcguire-steve** [comment]
Don't use the stock map server. 

https://mcguire-steve@bitbucket.org/hci7kspr16/ramrod.git
https://mcguire-steve@bitbucket.org/hci7kspr16/rqt_hri_view.git
https://mcguire-steve@bitbucket.org/hci7kspr16/rqt_hri_getpos.git
https://mcguire-steve@bitbucket.org/hci7kspr16/hri_map_server.git
https://mcguire-steve@bitbucket.org/hci7kspr16/basic_move_base.git

**Comment by ianloefgren** [comment]
hri_map_server solved the problem, but Steve, what exactly was the issue in the first place?

**Comment by mcguire-steve** [comment]
As I recall, there was an issue with SDL loading PBM files, such that a bitmap was interpreted with values from [0,1](or something like that) as opposed to [0,254]. What would happen is that it would be impossible to map occupied / clear with PBMs because I needed a threshold that couldn't be set. It was easier to clone the map_server code, although I probably should have just forked it. Line 131, image_loader.cpp.
